### PR TITLE
Feat: speech to text for TextInputs

### LINKED ISSUE #13: Add the audio form input feature.
Use any speech-to-text API to take input using speech

### PR DESCRIPTION
**Pull request by rkpattnaik780**
A panel will be displayed whenever a TextInput is focused. The panel will have options to provide input using speech to text and also recite the entered text.

Fixes #13

### CODE REVIEW

**Comment by rkpattnaik780** [comment]
> The buttons are not appearing on my end even on focus and as soon as I reload I'm getting asked to allow my microphone access. and is there any order the buttons should be clicked?

The buttons are appearing only for TextInputs, number and email types have been ignored for now. Regarding the microphone access, it is an overlooked bug. I will think of a workaround.

**Comment by manaswinidas** [comment]
@rkpattnaik780 it is not appearing for text inputs on my end. That's what I'm worried about. I already know that it shouldn't be coming for dates and number inputs.

**Comment by rkpattnaik780** [comment]
The latest commit tries to solve some of the existing problems. Please review again.

**Comment by rkpattnaik780** [comment]
> I have a suggestion on visibility of the speech buttons. Currently on clicking on other tabs like email and number, the panel is still visible below the first or last name. It will be better if the panels will be set to visible only when particular fields are clicked and if other fields are focused than it should be hidden again. This can be discussed further, just a suggestion from my side.

Has been addressed in the last commit.

**Comment by rkpattnaik780** [comment]
> There is one strange thing that I noticed. When I say "Das" it is printing "10", but reading it "ten". I am confused whether it is a bug or a feature

It is due to the flaws in the Web Speech API. Das is being interpreted as `Dus`(Hindi). Same goes for cases like 'aath'.

**Pull request merged**
